#!/bin/bash

gpu=$(optimus-manager --status | awk 'NR==3 { print $5 }')

monitor1=""
monitor2=""
monitor3=""

if [[ $gpu = 'hybrid' ]]; then
    monitor1="DP-1-0"
    monitor2="HDMI-1"
    monitor3="eDP-1"
fi
if [[ $gpu = 'nvidia' ]]; then
    monitor1="DP-0"
    monitor2="HDMI-1-1"
    monitor3="eDP-1-1"
fi
if [[ $gpu = 'integrated' ]]; then
    monitor1="DP-1-0"
    monitor2="HDMI-A-0"
    monitor3="eDP"
fi

hdmi=$(xrandr | grep ' connected' | grep $monitor2 | awk '{print $1}')
dp=$(xrandr | grep ' connected' | grep $monitor1 | awk '{print $1}')

if [ ! -z "$hdmi" ] && [ ! -z "$dp" ]; then
    xrandr --output "$monitor1" --mode 1280x720 --pos 0x0 --rotate normal --output "$monitor2" --mode 1920x1080 --pos 1280x0 --rotate normal --output "$monitor3" --mode 1920x1080 --pos 3360x0
    xdotool mousemove --screen 0 2400 540 &
    xdotool click 1 &
    echo "" $(optimus-manager --status | awk 'NR==3 { print $5 }')>'/suckless/dmenu/data/screenSelected'
fi

if [ ! -z "$hdmi" ] && [ -z "$dp" ]; then
    xrandr --output "$monitor2" --mode 3440x1440 --pos 0x0 --rotate normal --output "$monitor3" --mode 1920x1080 --pos 3440x0 --rotate normal
    xdotool mousemove --screen 0 960 540 &
    xdotool click 1 &
    echo "" $(optimus-manager --status | awk 'NR==3 { print $5 }')>'/suckless/dmenu/data/screenSelected'

fi

if [ -z "$hdmi" ] && [ ! -z "$dp" ]; then
    xrandr --output "$monitor1" --mode 1280x720 --pos 0x0 --rotate normal --output "$monitor3" --mode 1920x1080 --pos 1280x0 --rotate normal
    echo "" $(optimus-manager --status | awk 'NR==3 { print $5 }')>'/suckless/dmenu/data/screenSelected'

fi
if [ -z "$hdmi" ] && [ -z "$dp" ]; then
    xrandr --output "$monitor3" --mode 1920x1080
    setxkbmap -option altwin:swap_alt_win &
    echo "" $(optimus-manager --status | awk 'NR==3 { print $5 }')>'/suckless/dmenu/data/screenSelected'
fi
