#!/bin/sh

gpu=$(optimus-manager --status | awk 'NR==3 { print $5 }')

if [[ $gpu = 'hybrid' ]] || [[ $gpu = 'integrated' ]]; then
    hdmi_active=$(xrandr |grep ' connected' |grep 'HDMI' |awk '{print $1}')
    [[ ! -z "$hdmi_active" ]] && xrandr --output HDMI-1 --mode 3440x1440 --rate 99.99 --output eDP-1 --off
    [[ -z "$hdmi_active" ]] && xrandr --output eDP-1 --mode 1920x1080
else
    xrandr --output eDP-1-1 --off 
     HDMI-1-1 --auto
    echo "nvidia"
fi

